baseURL = "https://www.kosk1011.tokyo/"

theme = "hugo-primer"
languageCode = "ja"
title = "kosk1011 Blog"

hasCJKLanguage = true
summaryLength = 70

disqusShortname = "kosk1011-blog"

copyright = "&copy;kosk1011"

[permalinks]
  posts = "/:year/:month/:day/:title/"

[taxonomies]
  category = "categories"

[frontmatter]
# update sitemap.xml's lastmod datetime by file change time, instead of git.
lastmod = ["lastmod", ":fileModTime", ":default"]

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

[[menu.main]]
    name = "categories"
    url = "/categories/"
    weight = 2

[[menu.main]]
    name = "Info"
    url = "/info/"
    weight = 3

[[menu.main]]
    name = "Feed"
    url = "/index.xml"
    weight = 4

[params]
description = "kosk1011 Blog"
twitter = "sen_nen"

# You can use favicon by addin them manually.
useIcon = true
useTwitterCard = true

shareTo = ["Twitter", "Hatena", "Facebook"]
ShowFooterCredits = true

