baseurl = "http://example.com"
languageCode = "en"
title = "kosk1011 Blog"
copyright = "Your Site copyright"
paginate = 3

theme = "minimage"

[params]
  description = "Your site description"
  author = "kosk1011"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.global]]
    name = "tags"
    url = "/tags/"

[[menu.global]]
    name = "categories"
    url = "/categories/"

[[menu.footer]]
    name = "About"
    url = "/page/about/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
