version: 2.1
orbs:
  hugo: circleci/hugo@0.5.2
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - hugo/build:
          html-proofer: true
          version: '0.68.3'