jobs:
  deploy:
    docker:
      - image: circleci/node:12.18.2
    steps:
      - attach_workspace:
          at: site
      - run: sudo npm install netlify-cli -g
      - run: netlify deploy --site-id $NETLIFY_SITE_ID -p site/public/ --access-token $NETLIFY_ACCESS_TOKEN
version: 2.1
orbs:
  hugo: circleci/hugo@0.5.2
workflows:
  welcome:
    jobs:
      - hugo/build:
          html-proofer: false
          version: '0.68.3'
      - deploy:
        #  filters:
        #    branches:
        #      only: master
          requires:
            - hugo/build
